# Generated by Django 5.0.1 on 2024-03-22 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('course_sn', models.CharField(max_length=255)),
                ('course_fn', models.CharField(max_length=255)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('seater', models.IntegerField()),
                ('fees_pm', models.IntegerField()),
                ('food_status', models.IntegerField()),
                ('stay_from', models.DateField()),
                ('duration', models.IntegerField()),
                ('course', models.CharField(max_length=500)),
                ('reg_no', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=500)),
                ('middle_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=250)),
                ('contact_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('egy_contact_no', models.BigIntegerField()),
                ('guardian_name', models.CharField(max_length=500)),
                ('guardian_relation', models.CharField(max_length=500)),
                ('guardian_contact_no', models.BigIntegerField()),
                ('corres_address', models.CharField(max_length=500)),
                ('corres_city', models.CharField(max_length=500)),
                ('corres_state', models.CharField(max_length=500)),
                ('corres_pincode', models.IntegerField()),
                ('permanent_address', models.CharField(max_length=500)),
                ('permanent_city', models.CharField(max_length=500)),
                ('permanent_state', models.CharField(max_length=500)),
                ('permanent_pincode', models.IntegerField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seater', models.IntegerField()),
                ('room_no', models.IntegerField(unique=True)),
                ('fees', models.IntegerField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_ip', models.BinaryField(max_length=16)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updation_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.BinaryField(max_length=16)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.admin')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('contact_no', models.BigIntegerField()),
                ('updation_date', models.CharField(blank=True, max_length=45, null=True)),
                ('pass_update_date', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
