# Generated by Django 5.0.1 on 2024-03-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='pass_update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='updation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
