# Generated by Django 5.0.1 on 2024-03-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_userregistration_pass_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='permanent_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
