# Generated by Django 5.0.1 on 2024-03-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_registration_permanent_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.userregistration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlog',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
