# Generated by Django 5.0.1 on 2024-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_userlog_user_email_remove_userlog_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user_ip',
            field=models.CharField(max_length=16),
        ),
    ]
