# Generated by Django 5.0.1 on 2024-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_userlog_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='reg_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
